version: '3.7'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    networks:
      - local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - local

networks:
  local: